name: blocx
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  uuid: ^4.5.1
  bloc: ^9.0.0
  meta: 1.16.0
  bloc_concurrency: ^0.3.0
  stream_transform: ^2.1.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
